# Generated by Django 3.1.7 on 2021-03-20 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookJournalBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.BigIntegerField(verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookjournalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.bookjournalbase')),
                ('num_pages', models.IntegerField(verbose_name='Number Of Pages')),
                ('genre', models.TextField(verbose_name='Genre')),
            ],
            bases=('main.bookjournalbase',),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('bookjournalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.bookjournalbase')),
                ('type', models.TextField(verbose_name='Type')),
                ('publisher', models.TextField(max_length=100, verbose_name='Publisher')),
            ],
            bases=('main.bookjournalbase',),
        ),
    ]
